import { DayExercise } from './types';

export const exercisesData: DayExercise[] = [
  // FASE 1: Fundamentos (7 dias)
  {
    day: 1,
    phase: 1,
    title: 'Localização do Músculo PC',
    kegels: 'Identifique o músculo PC: durante a micção, tente interromper o fluxo de urina. O músculo que você contrai é o PC. Faça 3 séries de 10 contrações rápidas (1s contraído, 1s relaxado).',
    breathing: 'Respiração diafragmática: Deite-se, coloque uma mão no peito e outra na barriga. Inspire pelo nariz por 4s (barriga sobe), segure 2s, expire pela boca por 6s. Repita por 5 minutos.',
    mindfulness: 'Escaneamento corporal: Sente-se confortavelmente, feche os olhos e observe cada parte do corpo por 30s, da cabeça aos pés. Note tensões sem julgamento.',
    duration: 15,
    imageUrl: 'https://st5.depositphotos.com/3900811/61930/v/450/depositphotos_619301320-stock-illustration-pelvic-floor-muscles-anatomy-male.jpg'
  },
  {
    day: 2,
    phase: 1,
    title: 'Fortalecimento Básico',
    kegels: 'Contrações sustentadas: 3 séries de 5 contrações, segurando cada uma por 5 segundos. Descanse 10s entre séries.',
    breathing: 'Respiração 4-7-8: Inspire por 4s, segure por 7s, expire por 8s. Faça 10 ciclos. Essa técnica acalma o sistema nervoso.',
    mindfulness: 'Atenção plena na respiração: Foque apenas na sensação do ar entrando e saindo. Quando a mente divagar, traga gentilmente de volta.',
    duration: 15,
    imageUrl: 'https://i.ytimg.com/vi/DgsLVZYN8Xg/maxresdefault.jpg'
  },
  {
    day: 3,
    phase: 1,
    title: 'Ritmo e Controle',
    kegels: 'Contrações ritmadas: 2 séries de 15 contrações rápidas (1s on/off), depois 2 séries de 8 contrações lentas (5s contraído, 5s relaxado).',
    breathing: 'Respiração quadrada: Inspire 4s, segure 4s, expire 4s, segure 4s. Repita por 5 minutos. Visualize um quadrado enquanto respira.',
    mindfulness: 'Observação de pensamentos: Sente-se e observe seus pensamentos como nuvens passando. Não se apegue, apenas observe.',
    duration: 20,
    imageUrl: 'https://drconsulta.com/conteudo/wp-content/uploads/2023/12/dr.consulta-exercicios-de-kegel-para-homens-1024x576.webp'
  },
  {
    day: 4,
    phase: 1,
    title: 'Resistência Inicial',
    kegels: 'Aumento de resistência: 4 séries de 10 contrações sustentadas por 7 segundos cada. Descanse 15s entre séries.',
    breathing: 'Respiração alternada: Tape a narina direita, inspire pela esquerda por 4s. Tape a esquerda, expire pela direita por 4s. Alterne por 5 minutos.',
    mindfulness: 'Gratidão corporal: Agradeça mentalmente cada parte do seu corpo, reconhecendo sua função e importância.',
    duration: 20,
    optional: 'Pratique contrações PC durante atividades diárias (sentado, em pé).',
  },
  {
    day: 5,
    phase: 1,
    title: 'Integração Mente-Corpo',
    kegels: 'Contrações com visualização: Enquanto contrai, visualize energia subindo pela coluna. 3 séries de 12 contrações de 6s cada.',
    breathing: 'Respiração com contagem regressiva: Inspire por 5s, expire por 10s. A cada expiração, conte de 10 a 1 mentalmente.',
    mindfulness: 'Meditação guiada de 10 minutos: Foque em relaxar completamente, soltando tensões físicas e mentais.',
    duration: 25,
    imageUrl: 'https://i.ytimg.com/vi/y1HTRArPo_0/maxresdefault.jpg'
  },
  {
    day: 6,
    phase: 1,
    title: 'Controle Progressivo',
    kegels: 'Pirâmide de contrações: 1s, 2s, 3s, 4s, 5s, 4s, 3s, 2s, 1s (tempo de contração). Faça 3 pirâmides completas.',
    breathing: 'Respiração profunda com pausa: Inspire profundamente por 6s, segure 10s, expire lentamente por 8s. Repita 15 vezes.',
    mindfulness: 'Escaneamento de sensações: Observe sensações corporais sem rotular como boas ou ruins. Apenas sinta.',
    duration: 25,
    optional: 'Anote em um diário como se sente fisicamente e emocionalmente.',
  },
  {
    day: 7,
    phase: 1,
    title: 'Revisão e Consolidação',
    kegels: 'Teste de resistência: Contraia o PC e segure o máximo que conseguir (meta: 30s). Faça 5 tentativas com 30s de descanso.',
    breathing: 'Combinação de técnicas: Alterne entre respiração 4-7-8 e respiração quadrada. 3 minutos cada.',
    mindfulness: 'Reflexão da semana: Medite sobre o progresso, desafios e aprendizados. Celebre pequenas vitórias.',
    duration: 30,
    optional: 'Preencha o relatório da Fase 1: nota de força PC (1-10), principais dificuldades, observações.',
  },

  // FASE 2: Controle Ativo (14 dias)
  {
    day: 8,
    phase: 2,
    title: 'Contrações Avançadas',
    kegels: 'Contrações em ondas: Contraia gradualmente (20%, 40%, 60%, 80%, 100%), depois relaxe gradualmente. 4 séries de 8 ondas.',
    breathing: 'Respiração sincronizada: Inspire durante contração PC, expire durante relaxamento. 5 minutos contínuos.',
    mindfulness: 'Atenção plena nas sensações genitais: Observe sensações sem julgamento ou excitação. Apenas consciência.',
    duration: 25,
    imageUrl: 'https://st5.depositphotos.com/3900811/61930/v/450/depositphotos_619301320-stock-illustration-pelvic-floor-muscles-anatomy-male.jpg'
  },
  {
    day: 9,
    phase: 2,
    title: 'Técnica Start-Stop Mental',
    kegels: '5 séries de 15 contrações rápidas, depois 3 séries de 10 contrações de 10s cada.',
    breathing: 'Respiração de emergência: Pratique respiração 4-7-8 rápida (3 ciclos) para acalmar excitação. Repita 10 vezes.',
    mindfulness: 'Visualização de controle: Imagine uma escala de excitação de 1-10. Visualize-se mantendo em 7, sem subir para 8-9.',
    duration: 30,
    optional: 'Durante excitação real, pratique pausar e respirar antes de continuar.',
  },
  {
    day: 10,
    phase: 2,
    title: 'Resistência Máxima',
    kegels: 'Desafio de resistência: Contraia por 20s, relaxe 10s. Repita 10 vezes. Aumente 2s a cada série se possível.',
    breathing: 'Respiração profunda prolongada: Inspire por 8s, segure 12s, expire por 10s. Faça 12 ciclos.',
    mindfulness: 'Meditação de aceitação: Aceite sensações de excitação sem reagir impulsivamente. Observe-as passar.',
    duration: 30,
    imageUrl: 'https://drconsulta.com/conteudo/wp-content/uploads/2023/12/dr.consulta-exercicios-de-kegel-para-homens-1024x576.webp'
  },
  {
    day: 11,
    phase: 2,
    title: 'Controle em Movimento',
    kegels: 'Contrações dinâmicas: Faça contrações PC enquanto caminha, agacha ou se movimenta. 5 minutos de prática.',
    breathing: 'Respiração durante movimento: Sincronize respiração com passos (4 passos inspire, 6 passos expire).',
    mindfulness: 'Atenção plena em atividades: Escolha uma atividade diária e faça com total presença e consciência.',
    duration: 25,
    optional: 'Pratique contrações PC discretamente em diferentes contextos (trabalho, transporte).',
  },
  {
    day: 12,
    phase: 2,
    title: 'Técnica de Compressão',
    kegels: 'Compressão PC: Contraia fortemente por 3s, relaxe completamente por 3s. 5 séries de 20 repetições.',
    breathing: 'Respiração de resfriamento: Inspire pelo nariz, expire pela boca como se estivesse soprando vela. 8 minutos.',
    mindfulness: 'Escaneamento de excitação: Identifique sinais corporais de excitação crescente (respiração, tensão, calor).',
    duration: 30,
    imageUrl: 'https://i.ytimg.com/vi/y1HTRArPo_0/maxresdefault.jpg'
  },
  {
    day: 13,
    phase: 2,
    title: 'Simulação Realista',
    kegels: 'Contrações em cenário: Visualize situação íntima enquanto faz contrações. 4 séries de 12 contrações de 8s.',
    breathing: 'Respiração de controle: Quando visualizar excitação alta, use respiração 4-7-8 para reduzir. Pratique 10 ciclos.',
    mindfulness: 'Meditação de desapego: Observe excitação como observador externo, sem se identificar com ela.',
    duration: 35,
    optional: 'Pratique técnica start-stop durante masturbação: pare antes do ponto sem retorno, respire, continue.',
  },
  {
    day: 14,
    phase: 2,
    title: 'Integração Avançada',
    kegels: 'Combinação de técnicas: Alterne contrações rápidas (10x), lentas (5x de 10s), ondas (3x). Faça 4 rodadas.',
    breathing: 'Respiração adaptativa: Pratique mudar ritmo respiratório rapidamente (rápido para lento, lento para profundo).',
    mindfulness: 'Atenção plena em sensações prazerosas: Observe prazer sem urgência de atingir clímax. Apenas sinta.',
    duration: 35,
    imageUrl: 'https://i.ytimg.com/vi/DgsLVZYN8Xg/maxresdefault.jpg'
  },
  {
    day: 15,
    phase: 2,
    title: 'Controle Sob Pressão',
    kegels: 'Teste de estresse: Contraia PC enquanto visualiza situação de alta excitação. Mantenha 15s, relaxe 10s. 8 repetições.',
    breathing: 'Respiração de emergência avançada: Pratique acalmar excitação de 9/10 para 6/10 apenas com respiração. 5 tentativas.',
    mindfulness: 'Meditação de confiança: Visualize-se com controle total, confiante e relaxado em situações íntimas.',
    duration: 35,
    optional: 'Anote situações que desencadeiam ansiedade e pratique respiração preventiva.',
  },
  {
    day: 16,
    phase: 2,
    title: 'Refinamento de Técnica',
    kegels: 'Micro-contrações: Contrações muito leves (30% da força) por 30s contínuos. 5 séries.',
    breathing: 'Respiração sutil: Respirações quase imperceptíveis, lentas e profundas. Pratique por 10 minutos.',
    mindfulness: 'Observação de gatilhos: Identifique pensamentos/imagens que aceleram excitação. Observe sem reagir.',
    duration: 30,
    imageUrl: 'https://drconsulta.com/conteudo/wp-content/uploads/2023/12/dr.consulta-exercicios-de-kegel-para-homens-1024x576.webp'
  },
  {
    day: 17,
    phase: 2,
    title: 'Prática Realista Avançada',
    kegels: 'Contrações em ritmo variável: Alterne ritmos (rápido 10s, lento 20s, pausa 10s). 6 ciclos completos.',
    breathing: 'Respiração sincronizada com visualização: Respire enquanto visualiza controle perfeito em situação real.',
    mindfulness: 'Meditação de presença: Mantenha-se 100% presente no momento, sem antecipar clímax.',
    duration: 40,
    optional: 'Pratique técnica squeeze: aperte glande por 5s quando sentir ejaculação iminente.',
  },
  {
    day: 18,
    phase: 2,
    title: 'Consolidação de Habilidades',
    kegels: 'Rotina completa: 20 contrações rápidas, 10 lentas (10s), 5 ondas, 3 sustentadas (20s). Faça 3 rodadas.',
    breathing: 'Respiração master: Combine todas as técnicas aprendidas em sequência de 15 minutos.',
    mindfulness: 'Reflexão da Fase 2: Medite sobre evolução, compare com Fase 1, celebre progresso.',
    duration: 40,
    optional: 'Preencha relatório da Fase 2: nota de controle (1-10), situações desafiadoras, vitórias.',
  },
  {
    day: 19,
    phase: 2,
    title: 'Preparação para Fase 3',
    kegels: 'Teste de resistência final: Contraia o máximo possível (meta: 45s). Faça 5 tentativas.',
    breathing: 'Respiração de transição: Pratique acalmar-se de alta excitação para estado relaxado em menos de 1 minuto.',
    mindfulness: 'Visualização de sucesso: Imagine-se aplicando todas as técnicas com sucesso em situação real.',
    duration: 35,
    imageUrl: 'https://i.ytimg.com/vi/y1HTRArPo_0/maxresdefault.jpg'
  },
  {
    day: 20,
    phase: 2,
    title: 'Integração Total',
    kegels: 'Prática livre: Crie sua própria rotina combinando técnicas favoritas. 20 minutos de prática.',
    breathing: 'Respiração intuitiva: Respire de forma que pareça natural para controlar excitação. Confie no corpo.',
    mindfulness: 'Meditação de gratidão: Agradeça pelo progresso e compromisso com sua evolução.',
    duration: 40,
    optional: 'Revise anotações das fases anteriores e identifique padrões de sucesso.',
  },
  {
    day: 21,
    phase: 2,
    title: 'Revisão e Avaliação',
    kegels: 'Avaliação de força: Teste força PC em escala 1-10. Compare com Dia 1. Faça rotina completa de 25 minutos.',
    breathing: 'Respiração de maestria: Demonstre controle total sobre respiração em diferentes ritmos e profundidades.',
    mindfulness: 'Reflexão profunda: Medite sobre transformação pessoal, mudanças de mindset e próximos passos.',
    duration: 45,
    optional: 'Preencha relatório final da Fase 2 com detalhes sobre evolução e preparação para Fase 3.',
  },

  // FASE 3: Domínio Total (14 dias)
  {
    day: 22,
    phase: 3,
    title: 'Controle Absoluto Inicial',
    kegels: 'Contrações de precisão: Contraia em níveis específicos (25%, 50%, 75%, 100%) e mantenha por 10s cada. 5 séries.',
    breathing: 'Respiração de maestria: Controle total sobre inspiração/expiração com pausas variáveis. 15 minutos.',
    mindfulness: 'Meditação de domínio: Visualize-se com controle absoluto, confiante e presente em qualquer situação.',
    duration: 40,
    imageUrl: 'https://st5.depositphotos.com/3900811/61930/v/450/depositphotos_619301320-stock-illustration-pelvic-floor-muscles-anatomy-male.jpg'
  },
  {
    day: 23,
    phase: 3,
    title: 'Técnica Multi-Pausa',
    kegels: 'Contrações em série: 5 contrações de 15s com apenas 5s de descanso. Repita 6 vezes.',
    breathing: 'Respiração multi-fase: Inspire em 3 fases (baixo, médio, alto abdômen), expire em 3 fases. 10 minutos.',
    mindfulness: 'Atenção plena em múltiplos pontos: Observe simultaneamente respiração, PC e sensações corporais.',
    duration: 40,
    optional: 'Pratique técnica multi-pausa durante intimidade: pause 3-4 vezes antes do clímax.',
  },
  {
    day: 24,
    phase: 3,
    title: 'Resistência Extrema',
    kegels: 'Desafio máximo: Contraia por 60s, relaxe 20s. Repita 8 vezes. Foque em manter intensidade constante.',
    breathing: 'Respiração de endurance: Respirações longas e profundas (10s inspire, 15s expire) por 15 minutos.',
    mindfulness: 'Meditação de resistência: Observe desconforto/cansaço sem desistir. Cultive perseverança mental.',
    duration: 45,
    imageUrl: 'https://drconsulta.com/conteudo/wp-content/uploads/2023/12/dr.consulta-exercicios-de-kegel-para-homens-1024x576.webp'
  },
  {
    day: 25,
    phase: 3,
    title: 'Controle em Cenários Reais',
    kegels: 'Simulação completa: Visualize situação íntima completa enquanto faz contrações. Pause quando necessário. 30 minutos.',
    breathing: 'Respiração adaptativa real: Pratique ajustar respiração conforme "nível de excitação" na visualização.',
    mindfulness: 'Presença total: Mantenha-se 100% presente na visualização, observando sensações sem reagir impulsivamente.',
    duration: 50,
    optional: 'Aplique técnicas em situação real se possível. Anote resultados e ajustes necessários.',
  },
  {
    day: 26,
    phase: 3,
    title: 'Técnica de Redirecionamento',
    kegels: 'Contrações com redirecionamento: Ao sentir excitação alta, contraia PC forte por 10s e redirecione energia. 10 ciclos.',
    breathing: 'Respiração de redirecionamento: Inspire visualizando energia subindo pela coluna, expire liberando tensão.',
    mindfulness: 'Meditação de transmutação: Visualize energia sexual sendo transformada em vitalidade e confiança.',
    duration: 45,
    imageUrl: 'https://i.ytimg.com/vi/y1HTRArPo_0/maxresdefault.jpg'
  },
  {
    day: 27,
    phase: 3,
    title: 'Domínio Sob Pressão',
    kegels: 'Teste extremo: Contraia PC enquanto visualiza situação de máxima excitação. Mantenha controle. 20 minutos.',
    breathing: 'Respiração de emergência master: Reduza excitação de 10/10 para 5/10 em menos de 30s usando apenas respiração.',
    mindfulness: 'Meditação de desapego avançado: Observe excitação intensa sem identificação ou reação. Puro testemunho.',
    duration: 50,
    optional: 'Pratique edging avançado: chegue perto do clímax 5 vezes, pare e controle cada vez.',
  },
  {
    day: 28,
    phase: 3,
    title: 'Integração Mente-Corpo-Espírito',
    kegels: 'Contrações holísticas: Combine PC, respiração e visualização simultaneamente. 25 minutos de prática integrada.',
    breathing: 'Respiração transcendental: Respirações que conectam corpo, mente e intenção de controle total.',
    mindfulness: 'Meditação de unidade: Sinta-se uno com seu corpo, em total harmonia e controle.',
    duration: 50,
    imageUrl: 'https://i.ytimg.com/vi/DgsLVZYN8Xg/maxresdefault.jpg'
  },
  {
    day: 29,
    phase: 3,
    title: 'Prática de Performance',
    kegels: 'Simulação de performance: Visualize situação íntima completa, aplicando todas as técnicas. 35 minutos.',
    breathing: 'Respiração de performance: Mantenha controle respiratório perfeito durante toda a visualização.',
    mindfulness: 'Presença e confiança: Mantenha-se presente, confiante e no controle durante toda a prática.',
    duration: 55,
    optional: 'Aplique em situação real. Foque em prazer prolongado, não em performance perfeita.',
  },
  {
    day: 30,
    phase: 3,
    title: 'Refinamento Final',
    kegels: 'Micro-ajustes: Identifique pontos fracos e pratique especificamente. 30 minutos de prática focada.',
    breathing: 'Respiração personalizada: Crie seu próprio padrão respiratório que funciona melhor para você.',
    mindfulness: 'Meditação de auto-conhecimento: Reflita sobre o que aprendeu sobre seu corpo e mente.',
    duration: 50,
    imageUrl: 'https://drconsulta.com/conteudo/wp-content/uploads/2023/12/dr.consulta-exercicios-de-kegel-para-homens-1024x576.webp'
  },
  {
    day: 31,
    phase: 3,
    title: 'Teste de Maestria',
    kegels: 'Avaliação final: Teste todas as habilidades adquiridas. Contraia por 90s, faça ondas perfeitas, controle total. 40 minutos.',
    breathing: 'Respiração master final: Demonstre domínio completo sobre respiração em qualquer situação.',
    mindfulness: 'Meditação de celebração: Celebre sua jornada, transformação e novo nível de controle.',
    duration: 60,
    optional: 'Preencha avaliação final: compare Dia 1 vs Dia 31 em força PC, controle, confiança.',
  },
  {
    day: 32,
    phase: 3,
    title: 'Aplicação Real Avançada',
    kegels: 'Prática em contexto real: Aplique técnicas em situação íntima real. Foque em presença e controle.',
    breathing: 'Respiração natural integrada: Use respiração de forma natural e intuitiva durante intimidade.',
    mindfulness: 'Presença total: Esteja 100% presente, conectado e no controle durante toda a experiência.',
    duration: 45,
    optional: 'Anote resultados, sensações e áreas para continuar melhorando.',
  },
  {
    day: 33,
    phase: 3,
    title: 'Consolidação de Domínio',
    kegels: 'Rotina de manutenção: Crie rotina de 20 minutos que você pode fazer 3x por semana após o programa.',
    breathing: 'Respiração de manutenção: Defina prática respiratória diária de 5 minutos para manter habilidades.',
    mindfulness: 'Meditação de compromisso: Comprometa-se com prática contínua e evolução constante.',
    duration: 45,
    imageUrl: 'https://i.ytimg.com/vi/y1HTRArPo_0/maxresdefault.jpg'
  },
  {
    day: 34,
    phase: 3,
    title: 'Preparação para Autonomia',
    kegels: 'Prática autônoma: Faça sua rotina personalizada sem guia. Confie em seu conhecimento e intuição.',
    breathing: 'Respiração intuitiva avançada: Respire de forma que seu corpo pede, sem seguir padrões rígidos.',
    mindfulness: 'Meditação de auto-confiança: Reconheça sua capacidade de manter controle sem dependência externa.',
    duration: 40,
    optional: 'Revise todo o programa e identifique técnicas favoritas para rotina de manutenção.',
  },
  {
    day: 35,
    phase: 3,
    title: 'Celebração e Novo Começo',
    kegels: 'Celebração final: Faça rotina completa celebrando cada contração como símbolo de sua evolução. 30 minutos.',
    breathing: 'Respiração de gratidão: Respire com gratidão por seu corpo, mente e dedicação ao programa.',
    mindfulness: 'Meditação de transformação: Reflita sobre quem você era no Dia 1 e quem você é agora. Celebre!',
    duration: 45,
    optional: 'Preencha relatório final completo. Defina metas de manutenção. Bem-vindo ao 1%!',
  },
];

export const getBadges = (): Array<{id: string, title: string, description: string, requirement: number}> => [
  { id: 'first-day', title: 'Primeiro Passo', description: 'Completou o Dia 1', requirement: 1 },
  { id: 'week-warrior', title: 'Guerreiro da Semana', description: 'Completou 7 dias consecutivos', requirement: 7 },
  { id: 'phase-1-master', title: 'Mestre dos Fundamentos', description: 'Completou a Fase 1', requirement: 7 },
  { id: 'halfway-hero', title: 'Herói do Meio Caminho', description: 'Completou 50% do programa', requirement: 18 },
  { id: 'phase-2-master', title: 'Mestre do Controle Ativo', description: 'Completou a Fase 2', requirement: 21 },
  { id: 'final-stretch', title: 'Reta Final', description: 'Faltam apenas 7 dias', requirement: 28 },
  { id: 'phase-3-master', title: 'Mestre do Domínio Total', description: 'Completou a Fase 3', requirement: 35 },
  { id: 'the-one-percent', title: 'Bem-vindo ao 1%', description: 'Completou todos os 35 dias!', requirement: 35 },
];
